// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class PixconvertCUDA {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  PixconvertCUDA(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  PixconvertCUDA.fromLookup(ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup)
      : _lookup = lookup;

  int add(
    int a,
    int b,
  ) {
    return _add(
      a,
      b,
    );
  }

  late final _addPtr = _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int32, ffi.Int32)>>('add');
  late final _add = _addPtr.asFunction<int Function(int, int)>();

  void uyvyToRGBA(
    int width,
    int height,
    ffi.Pointer<ffi.Uint8> src,
    ffi.Pointer<ffi.Uint8> dest,
  ) {
    return _uyvyToRGBA(
      width,
      height,
      src,
      dest,
    );
  }

  late final _uyvyToRGBAPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int32, ffi.Int32, ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>>(
      'uyvyToRGBA');
  late final _uyvyToRGBA =
      _uyvyToRGBAPtr.asFunction<void Function(int, int, ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>();

  void rgbaToWaveform(
    int srcWidth,
    int srcHeight,
    ffi.Pointer<ffi.Uint8> src,
    int wfWidth,
    int wfHeight,
    ffi.Pointer<ffi.Uint8> dest,
  ) {
    return _rgbaToWaveform(
      srcWidth,
      srcHeight,
      src,
      wfWidth,
      wfHeight,
      dest,
    );
  }

  late final _rgbaToWaveformPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int32, ffi.Int32, ffi.Pointer<ffi.Uint8>, ffi.Int32, ffi.Int32,
              ffi.Pointer<ffi.Uint8>)>>('rgbaToWaveform');
  late final _rgbaToWaveform = _rgbaToWaveformPtr
      .asFunction<void Function(int, int, ffi.Pointer<ffi.Uint8>, int, int, ffi.Pointer<ffi.Uint8>)>();

  void uyvyToScopes(
      int srcWidth,
      int srcHeight,
      ffi.Pointer<ffi.Uint8> src,
      ffi.Pointer<ffi.Uint8> dest,
      int scopeWidth,
      int scopeHeight,
      ffi.Pointer<ffi.Uint8> wf,
      ffi.Pointer<ffi.Uint8> wfRgb,
      ffi.Pointer<ffi.Uint8> wfParade,
      ffi.Pointer<ffi.Uint8> vScope) {
    return _uyvyToScopes(srcWidth, srcHeight, src, dest, scopeWidth, scopeHeight, wf, wfRgb, wfParade, vScope);
  }

  late final _uyvyToScopesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int32,
              ffi.Int32,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Int32,
              ffi.Int32,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>)>>("uyvyToScopes");

  late final _uyvyToScopes = _uyvyToScopesPtr.asFunction<
      void Function(int, int, ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>, int, int, ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>();

  void getDeviceProperties(
    ffi.Pointer<ffi.Int32> major,
    ffi.Pointer<ffi.Int32> minor,
  ) {
    return _getDeviceProperties(major, minor);
  }

  late final _getDevicePropertiesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Int32>, ffi.Pointer<ffi.Int32>)>>(
          "getDeviceProperties");

  late final _getDeviceProperties =
      _getDevicePropertiesPtr.asFunction<void Function(ffi.Pointer<ffi.Int32>, ffi.Pointer<ffi.Int32>)>();
}
