// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_field

import 'dart:ffi' as ffi;

import 'package:flutter/material.dart';

class PixconvertCUDA {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  PixconvertCUDA(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  PixconvertCUDA.fromLookup(ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup)
      : _lookup = lookup;

  late final _rgbaToWaveformPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int32, ffi.Int32, ffi.Pointer<ffi.Uint8>, ffi.Int32, ffi.Int32,
              ffi.Pointer<ffi.Uint8>)>>('rgbaToWaveform');
  late final _rgbaToWaveform = _rgbaToWaveformPtr
      .asFunction<void Function(int, int, ffi.Pointer<ffi.Uint8>, int, int, ffi.Pointer<ffi.Uint8>)>();

  void uyvyToScopes(
      int srcWidth,
      int srcHeight,
      ffi.Pointer<ffi.Uint8> src,
      ffi.Pointer<ffi.Uint8> dest,
      int scopeWidth,
      int scopeHeight,
      ffi.Pointer<ffi.Uint8> wf,
      ffi.Pointer<ffi.Uint8> wfRgb,
      ffi.Pointer<ffi.Uint8> wfParade,
      ffi.Pointer<ffi.Uint8> vScope) {
    return _uyvyToScopes(srcWidth, srcHeight, src, dest, scopeWidth, scopeHeight, wf, wfRgb, wfParade, vScope);
  }

  late final _uyvyToScopesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int32,
              ffi.Int32,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Int32,
              ffi.Int32,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>)>>("uyvyToScopes");

  late final _uyvyToScopes = _uyvyToScopesPtr.asFunction<
      void Function(int, int, ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>, int, int, ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>();

  void bgraToScopes(
      int srcWidth,
      int srcHeight,
      ffi.Pointer<ffi.Uint8> src,
      ffi.Pointer<ffi.Uint8> dest,
      int scopeWidth,
      int scopeHeight,
      ffi.Pointer<ffi.Uint8> wf,
      ffi.Pointer<ffi.Uint8> wfRgb,
      ffi.Pointer<ffi.Uint8> wfParade,
      ffi.Pointer<ffi.Uint8> vScope) {
    return _bgraToScopes(srcWidth, srcHeight, src, dest, scopeWidth, scopeHeight, wf, wfRgb, wfParade, vScope);
  }

  late final _bgraToScopesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int32,
              ffi.Int32,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Int32,
              ffi.Int32,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>)>>("bgraToScopes");

  late final _bgraToScopes = _bgraToScopesPtr.asFunction<
      void Function(int, int, ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>, int, int, ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>();

  void getDeviceProperties(
    ffi.Pointer<ffi.Int32> major,
    ffi.Pointer<ffi.Int32> minor,
  ) {
    return _getDeviceProperties(major, minor);
  }

  late final _getDevicePropertiesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Int32>, ffi.Pointer<ffi.Int32>)>>(
          "getDeviceProperties");

  late final _getDeviceProperties =
      _getDevicePropertiesPtr.asFunction<void Function(ffi.Pointer<ffi.Int32>, ffi.Pointer<ffi.Int32>)>();

  //void rectMaskFrame(int fWidth, int fHeight, int mLeft, int mTop, int mWidth, int mHeight, uint8_t *frame, int format)

  /// format: 1 = UYVY | 2 = BGRA
  void rectMaskFrame(Size frameSize, Rect mask, ffi.Pointer<ffi.Uint8> frame, int format) {
    return _rectMaskFrame(
      frameSize.width.toInt(),
      frameSize.height.toInt(),
      mask.left.toInt(),
      mask.top.toInt(),
      mask.width.toInt(),
      mask.height.toInt(),
      frame,
      format,
    );
  }

  late final _rectMaskFramePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
    ffi.Int32,
    ffi.Int32,
    ffi.Int32,
    ffi.Int32,
    ffi.Int32,
    ffi.Int32,
    ffi.Pointer<ffi.Uint8>,
    ffi.Int32,
  )>>("rectMaskFrame");

  late final _rectMaskFrame = _rectMaskFramePtr.asFunction<
      void Function(
    int fWidth,
    int fHeight,
    int mLeft,
    int mTop,
    int mWidth,
    int mHeight,
    ffi.Pointer<ffi.Uint8> frame,
    int format,
  )>();

  void thumbnailFromUyvy(
    ffi.Pointer<ffi.Uint8> src,
    int srcWidth,
    int srcHeight,
    ffi.Pointer<ffi.Uint8> tn,
    int tnWidth,
    int tnHeight,
  ) {
    return _thumbnailFromUyvy(src, srcWidth, srcHeight, tn, tnWidth, tnHeight);
  }

  late final _thumbnailFromUyvyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Int32,
    ffi.Int32,
    ffi.Pointer<ffi.Uint8>,
    ffi.Int32,
    ffi.Int32,
  )>>("thumbnailFromUyvy");

  late final _thumbnailFromUyvy = _thumbnailFromUyvyPtr.asFunction<
      void Function(
    ffi.Pointer<ffi.Uint8> src,
    int srcWidth,
    int srcHeight,
    ffi.Pointer<ffi.Uint8> tn,
    int tnWidth,
    int tnHeight,
  )>();

  void thumbnailFromBgra(
    ffi.Pointer<ffi.Uint8> src,
    int srcWidth,
    int srcHeight,
    ffi.Pointer<ffi.Uint8> tn,
    int tnWidth,
    int tnHeight,
  ) {
    return _thumbnailFromBgra(src, srcWidth, srcHeight, tn, tnWidth, tnHeight);
  }

  late final _thumbnailFromBgraPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Int32,
    ffi.Int32,
    ffi.Pointer<ffi.Uint8>,
    ffi.Int32,
    ffi.Int32,
  )>>("thumbnailFromBgra");

  late final _thumbnailFromBgra = _thumbnailFromBgraPtr.asFunction<
      void Function(
    ffi.Pointer<ffi.Uint8> src,
    int srcWidth,
    int srcHeight,
    ffi.Pointer<ffi.Uint8> tn,
    int tnWidth,
    int tnHeight,
  )>();
}
