// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class Pixconvert {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Pixconvert(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Pixconvert.fromLookup(ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup) : _lookup = lookup;

  int clampUint8(
    int v,
  ) {
    return _clampUint8(
      v,
    );
  }

  late final _clampUint8Ptr = _lookup<ffi.NativeFunction<ffi.Uint8 Function(ffi.Int32)>>('clampUint8');
  late final _clampUint8 = _clampUint8Ptr.asFunction<int Function(int)>();

  void uyvyToRGBA(
    int width,
    int height,
    ffi.Pointer<ffi.Uint8> src,
    ffi.Pointer<ffi.Uint8> dest,
  ) {
    return _uyvyToRGBA(
      width,
      height,
      src,
      dest,
    );
  }

  late final _uyvyToRGBAPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int32, ffi.Int32, ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>>(
      'uyvyToRGBA');
  late final _uyvyToRGBA =
      _uyvyToRGBAPtr.asFunction<void Function(int, int, ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>();

  void bgraToRGBA(
    int width,
    int height,
    ffi.Pointer<ffi.Uint8> data,
    ffi.Pointer<ffi.Uint8> dest,
  ) {
    return _bgraToRGBA(
      width,
      height,
      data,
      dest,
    );
  }

  late final _bgraToRGBAPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int32, ffi.Int32, ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>>(
      'bgraToRGBA');
  late final _bgraToRGBA =
      _bgraToRGBAPtr.asFunction<void Function(int, int, ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>();

  void rgbaToWaveform(
    int srcWidth,
    int srcHeight,
    ffi.Pointer<ffi.Uint8> src,
    int wfWidth,
    int wfHeight,
    ffi.Pointer<ffi.Uint8> dest,
  ) {
    return _rgbaToWaveform(
      srcWidth,
      srcHeight,
      src,
      wfWidth,
      wfHeight,
      dest,
    );
  }

  late final _rgbaToWaveformPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int32, ffi.Int32, ffi.Pointer<ffi.Uint8>, ffi.Int32, ffi.Int32,
              ffi.Pointer<ffi.Uint8>)>>('rgbaToWaveform');
  late final _rgbaToWaveform = _rgbaToWaveformPtr
      .asFunction<void Function(int, int, ffi.Pointer<ffi.Uint8>, int, int, ffi.Pointer<ffi.Uint8>)>();
}
