// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: non_constant_identifier_names

import 'dart:ffi' as ffi;

/// Portaudio FFI Bindings
class PortAudioFFI {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  PortAudioFFI(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  PortAudioFFI.fromLookup(ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup)
      : _lookup = lookup;

  /// Retrieve the release number of the currently running PortAudio build.
  /// For example, for version "19.5.1" this will return 0x00130501.
  ///
  /// @see paMakeVersionNumber
  int Pa_GetVersion() {
    return _Pa_GetVersion();
  }

  late final _Pa_GetVersionPtr = _lookup<ffi.NativeFunction<ffi.Int32 Function()>>('Pa_GetVersion');
  late final _Pa_GetVersion = _Pa_GetVersionPtr.asFunction<int Function()>();

  /// Retrieve a textual description of the current PortAudio build,
  /// e.g. "PortAudio V19.5.0-devel, revision 1952M".
  /// The format of the text may change in the future. Do not try to parse the
  /// returned string.
  ///
  /// @deprecated As of 19.5.0, use Pa_GetVersionInfo()->versionText instead.
  ffi.Pointer<ffi.Int8> Pa_GetVersionText() {
    return _Pa_GetVersionText();
  }

  late final _Pa_GetVersionTextPtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int8> Function()>>('Pa_GetVersionText');
  late final _Pa_GetVersionText = _Pa_GetVersionTextPtr.asFunction<ffi.Pointer<ffi.Int8> Function()>();

  /// Retrieve version information for the currently running PortAudio build.
  /// @return A pointer to an immutable PaVersionInfo structure.
  ///
  /// @note This function can be called at any time. It does not require PortAudio
  /// to be initialized. The structure pointed to is statically allocated. Do not
  /// attempt to free it or modify it.
  ///
  /// @see PaVersionInfo, paMakeVersionNumber
  /// @version Available as of 19.5.0.
  ffi.Pointer<PaVersionInfo> Pa_GetVersionInfo() {
    return _Pa_GetVersionInfo();
  }

  late final _Pa_GetVersionInfoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<PaVersionInfo> Function()>>('Pa_GetVersionInfo');
  late final _Pa_GetVersionInfo = _Pa_GetVersionInfoPtr.asFunction<ffi.Pointer<PaVersionInfo> Function()>();

  /// Translate the supplied PortAudio error code into a human readable
  /// message.
  ffi.Pointer<ffi.Int8> Pa_GetErrorText(
    int errorCode,
  ) {
    return _Pa_GetErrorText(
      errorCode,
    );
  }

  late final _Pa_GetErrorTextPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int8> Function(PaError)>>('Pa_GetErrorText');
  late final _Pa_GetErrorText = _Pa_GetErrorTextPtr.asFunction<ffi.Pointer<ffi.Int8> Function(int)>();

  /// Library initialization function - call this before using PortAudio.
  /// This function initializes internal data structures and prepares underlying
  /// host APIs for use.  With the exception of Pa_GetVersion(), Pa_GetVersionText(),
  /// and Pa_GetErrorText(), this function MUST be called before using any other
  /// PortAudio API functions.
  ///
  /// If Pa_Initialize() is called multiple times, each successful
  /// call must be matched with a corresponding call to Pa_Terminate().
  /// Pairs of calls to Pa_Initialize()/Pa_Terminate() may overlap, and are not
  /// required to be fully nested.
  ///
  /// Note that if Pa_Initialize() returns an error code, Pa_Terminate() should
  /// NOT be called.
  ///
  /// @return paNoError if successful, otherwise an error code indicating the cause
  /// of failure.
  ///
  /// @see Pa_Terminate
  int Pa_Initialize() {
    return _Pa_Initialize();
  }

  late final _Pa_InitializePtr = _lookup<ffi.NativeFunction<PaError Function()>>('Pa_Initialize');
  late final _Pa_Initialize = _Pa_InitializePtr.asFunction<int Function()>();

  /// Library termination function - call this when finished using PortAudio.
  /// This function deallocates all resources allocated by PortAudio since it was
  /// initialized by a call to Pa_Initialize(). In cases where Pa_Initialise() has
  /// been called multiple times, each call must be matched with a corresponding call
  /// to Pa_Terminate(). The final matching call to Pa_Terminate() will automatically
  /// close any PortAudio streams that are still open.
  ///
  /// Pa_Terminate() MUST be called before exiting a program which uses PortAudio.
  /// Failure to do so may result in serious resource leaks, such as audio devices
  /// not being available until the next reboot.
  ///
  /// @return paNoError if successful, otherwise an error code indicating the cause
  /// of failure.
  ///
  /// @see Pa_Initialize
  int Pa_Terminate() {
    return _Pa_Terminate();
  }

  late final _Pa_TerminatePtr = _lookup<ffi.NativeFunction<PaError Function()>>('Pa_Terminate');
  late final _Pa_Terminate = _Pa_TerminatePtr.asFunction<int Function()>();

  /// Retrieve the number of available host APIs. Even if a host API is
  /// available it may have no devices available.
  ///
  /// @return A non-negative value indicating the number of available host APIs
  /// or, a PaErrorCode (which are always negative) if PortAudio is not initialized
  /// or an error is encountered.
  ///
  /// @see PaHostApiIndex
  int Pa_GetHostApiCount() {
    return _Pa_GetHostApiCount();
  }

  late final _Pa_GetHostApiCountPtr = _lookup<ffi.NativeFunction<PaHostApiIndex Function()>>('Pa_GetHostApiCount');
  late final _Pa_GetHostApiCount = _Pa_GetHostApiCountPtr.asFunction<int Function()>();

  /// Retrieve the index of the default host API. The default host API will be
  /// the lowest common denominator host API on the current platform and is
  /// unlikely to provide the best performance.
  ///
  /// @return A non-negative value ranging from 0 to (Pa_GetHostApiCount()-1)
  /// indicating the default host API index or, a PaErrorCode (which are always
  /// negative) if PortAudio is not initialized or an error is encountered.
  int Pa_GetDefaultHostApi() {
    return _Pa_GetDefaultHostApi();
  }

  late final _Pa_GetDefaultHostApiPtr = _lookup<ffi.NativeFunction<PaHostApiIndex Function()>>('Pa_GetDefaultHostApi');
  late final _Pa_GetDefaultHostApi = _Pa_GetDefaultHostApiPtr.asFunction<int Function()>();

  /// Retrieve a pointer to a structure containing information about a specific
  /// host Api.
  ///
  /// @param hostApi A valid host API index ranging from 0 to (Pa_GetHostApiCount()-1)
  ///
  /// @return A pointer to an immutable PaHostApiInfo structure describing
  /// a specific host API. If the hostApi parameter is out of range or an error
  /// is encountered, the function returns NULL.
  ///
  /// The returned structure is owned by the PortAudio implementation and must not
  /// be manipulated or freed. The pointer is only guaranteed to be valid between
  /// calls to Pa_Initialize() and Pa_Terminate().
  ffi.Pointer<PaHostApiInfo> Pa_GetHostApiInfo(
    int hostApi,
  ) {
    return _Pa_GetHostApiInfo(
      hostApi,
    );
  }

  late final _Pa_GetHostApiInfoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<PaHostApiInfo> Function(PaHostApiIndex)>>('Pa_GetHostApiInfo');
  late final _Pa_GetHostApiInfo = _Pa_GetHostApiInfoPtr.asFunction<ffi.Pointer<PaHostApiInfo> Function(int)>();

  /// Convert a static host API unique identifier, into a runtime
  /// host API index.
  ///
  /// @param type A unique host API identifier belonging to the PaHostApiTypeId
  /// enumeration.
  ///
  /// @return A valid PaHostApiIndex ranging from 0 to (Pa_GetHostApiCount()-1) or,
  /// a PaErrorCode (which are always negative) if PortAudio is not initialized
  /// or an error is encountered.
  ///
  /// The paHostApiNotFound error code indicates that the host API specified by the
  /// type parameter is not available.
  ///
  /// @see PaHostApiTypeId
  int Pa_HostApiTypeIdToHostApiIndex(
    int type,
  ) {
    return _Pa_HostApiTypeIdToHostApiIndex(
      type,
    );
  }

  late final _Pa_HostApiTypeIdToHostApiIndexPtr =
      _lookup<ffi.NativeFunction<PaHostApiIndex Function(ffi.Int32)>>('Pa_HostApiTypeIdToHostApiIndex');
  late final _Pa_HostApiTypeIdToHostApiIndex = _Pa_HostApiTypeIdToHostApiIndexPtr.asFunction<int Function(int)>();

  /// Convert a host-API-specific device index to standard PortAudio device index.
  /// This function may be used in conjunction with the deviceCount field of
  /// PaHostApiInfo to enumerate all devices for the specified host API.
  ///
  /// @param hostApi A valid host API index ranging from 0 to (Pa_GetHostApiCount()-1)
  ///
  /// @param hostApiDeviceIndex A valid per-host device index in the range
  /// 0 to (Pa_GetHostApiInfo(hostApi)->deviceCount-1)
  ///
  /// @return A non-negative PaDeviceIndex ranging from 0 to (Pa_GetDeviceCount()-1)
  /// or, a PaErrorCode (which are always negative) if PortAudio is not initialized
  /// or an error is encountered.
  ///
  /// A paInvalidHostApi error code indicates that the host API index specified by
  /// the hostApi parameter is out of range.
  ///
  /// A paInvalidDevice error code indicates that the hostApiDeviceIndex parameter
  /// is out of range.
  ///
  /// @see PaHostApiInfo
  int Pa_HostApiDeviceIndexToDeviceIndex(
    int hostApi,
    int hostApiDeviceIndex,
  ) {
    return _Pa_HostApiDeviceIndexToDeviceIndex(
      hostApi,
      hostApiDeviceIndex,
    );
  }

  late final _Pa_HostApiDeviceIndexToDeviceIndexPtr =
      _lookup<ffi.NativeFunction<PaDeviceIndex Function(PaHostApiIndex, ffi.Int32)>>(
          'Pa_HostApiDeviceIndexToDeviceIndex');
  late final _Pa_HostApiDeviceIndexToDeviceIndex =
      _Pa_HostApiDeviceIndexToDeviceIndexPtr.asFunction<int Function(int, int)>();

  /// Return information about the last host error encountered. The error
  /// information returned by Pa_GetLastHostErrorInfo() will never be modified
  /// asynchronously by errors occurring in other PortAudio owned threads
  /// (such as the thread that manages the stream callback.)
  ///
  /// This function is provided as a last resort, primarily to enhance debugging
  /// by providing clients with access to all available error information.
  ///
  /// @return A pointer to an immutable structure constraining information about
  /// the host error. The values in this structure will only be valid if a
  /// PortAudio function has previously returned the paUnanticipatedHostError
  /// error code.
  ffi.Pointer<PaHostErrorInfo> Pa_GetLastHostErrorInfo() {
    return _Pa_GetLastHostErrorInfo();
  }

  late final _Pa_GetLastHostErrorInfoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<PaHostErrorInfo> Function()>>('Pa_GetLastHostErrorInfo');
  late final _Pa_GetLastHostErrorInfo =
      _Pa_GetLastHostErrorInfoPtr.asFunction<ffi.Pointer<PaHostErrorInfo> Function()>();

  /// Retrieve the number of available devices. The number of available devices
  /// may be zero.
  ///
  /// @return A non-negative value indicating the number of available devices or,
  /// a PaErrorCode (which are always negative) if PortAudio is not initialized
  /// or an error is encountered.
  int Pa_GetDeviceCount() {
    return _Pa_GetDeviceCount();
  }

  late final _Pa_GetDeviceCountPtr = _lookup<ffi.NativeFunction<PaDeviceIndex Function()>>('Pa_GetDeviceCount');
  late final _Pa_GetDeviceCount = _Pa_GetDeviceCountPtr.asFunction<int Function()>();

  /// Retrieve the index of the default input device. The result can be
  /// used in the inputDevice parameter to Pa_OpenStream().
  ///
  /// @return The default input device index for the default host API, or paNoDevice
  /// if no default input device is available or an error was encountered.
  int Pa_GetDefaultInputDevice() {
    return _Pa_GetDefaultInputDevice();
  }

  late final _Pa_GetDefaultInputDevicePtr =
      _lookup<ffi.NativeFunction<PaDeviceIndex Function()>>('Pa_GetDefaultInputDevice');
  late final _Pa_GetDefaultInputDevice = _Pa_GetDefaultInputDevicePtr.asFunction<int Function()>();

  /// Retrieve the index of the default output device. The result can be
  /// used in the outputDevice parameter to Pa_OpenStream().
  ///
  /// @return The default output device index for the default host API, or paNoDevice
  /// if no default output device is available or an error was encountered.
  ///
  /// @note
  /// On the PC, the user can specify a default device by
  /// setting an environment variable. For example, to use device #1.
  /// <pre>
  /// set PA_RECOMMENDED_OUTPUT_DEVICE=1
  /// </pre>
  /// The user should first determine the available device ids by using
  /// the supplied application "pa_devs".
  int Pa_GetDefaultOutputDevice() {
    return _Pa_GetDefaultOutputDevice();
  }

  late final _Pa_GetDefaultOutputDevicePtr =
      _lookup<ffi.NativeFunction<PaDeviceIndex Function()>>('Pa_GetDefaultOutputDevice');
  late final _Pa_GetDefaultOutputDevice = _Pa_GetDefaultOutputDevicePtr.asFunction<int Function()>();

  /// Retrieve a pointer to a PaDeviceInfo structure containing information
  /// about the specified device.
  /// @return A pointer to an immutable PaDeviceInfo structure. If the device
  /// parameter is out of range the function returns NULL.
  ///
  /// @param device A valid device index in the range 0 to (Pa_GetDeviceCount()-1)
  ///
  /// @note PortAudio manages the memory referenced by the returned pointer,
  /// the client must not manipulate or free the memory. The pointer is only
  /// guaranteed to be valid between calls to Pa_Initialize() and Pa_Terminate().
  ///
  /// @see PaDeviceInfo, PaDeviceIndex
  ffi.Pointer<PaDeviceInfo> Pa_GetDeviceInfo(
    int device,
  ) {
    return _Pa_GetDeviceInfo(
      device,
    );
  }

  late final _Pa_GetDeviceInfoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<PaDeviceInfo> Function(PaDeviceIndex)>>('Pa_GetDeviceInfo');
  late final _Pa_GetDeviceInfo = _Pa_GetDeviceInfoPtr.asFunction<ffi.Pointer<PaDeviceInfo> Function(int)>();

  /// Determine whether it would be possible to open a stream with the specified
  /// parameters.
  ///
  /// @param inputParameters A structure that describes the input parameters used to
  /// open a stream. The suggestedLatency field is ignored. See PaStreamParameters
  /// for a description of these parameters. inputParameters must be NULL for
  /// output-only streams.
  ///
  /// @param outputParameters A structure that describes the output parameters used
  /// to open a stream. The suggestedLatency field is ignored. See PaStreamParameters
  /// for a description of these parameters. outputParameters must be NULL for
  /// input-only streams.
  ///
  /// @param sampleRate The required sampleRate. For full-duplex streams it is the
  /// sample rate for both input and output
  ///
  /// @return Returns 0 if the format is supported, and an error code indicating why
  /// the format is not supported otherwise. The constant paFormatIsSupported is
  /// provided to compare with the return value for success.
  ///
  /// @see paFormatIsSupported, PaStreamParameters
  int Pa_IsFormatSupported(
    ffi.Pointer<PaStreamParameters> inputParameters,
    ffi.Pointer<PaStreamParameters> outputParameters,
    double sampleRate,
  ) {
    return _Pa_IsFormatSupported(
      inputParameters,
      outputParameters,
      sampleRate,
    );
  }

  late final _Pa_IsFormatSupportedPtr = _lookup<
      ffi.NativeFunction<
          PaError Function(
              ffi.Pointer<PaStreamParameters>, ffi.Pointer<PaStreamParameters>, ffi.Double)>>('Pa_IsFormatSupported');
  late final _Pa_IsFormatSupported = _Pa_IsFormatSupportedPtr.asFunction<
      int Function(ffi.Pointer<PaStreamParameters>, ffi.Pointer<PaStreamParameters>, double)>();

  /// Opens a stream for either input, output or both.
  ///
  /// @param stream The address of a PaStream pointer which will receive
  /// a pointer to the newly opened stream.
  ///
  /// @param inputParameters A structure that describes the input parameters used by
  /// the opened stream. See PaStreamParameters for a description of these parameters.
  /// inputParameters must be NULL for output-only streams.
  ///
  /// @param outputParameters A structure that describes the output parameters used by
  /// the opened stream. See PaStreamParameters for a description of these parameters.
  /// outputParameters must be NULL for input-only streams.
  ///
  /// @param sampleRate The desired sampleRate. For full-duplex streams it is the
  /// sample rate for both input and output. Note that the actual sampleRate
  /// may differ very slightly from the desired rate because of hardware limitations.
  /// The exact rate can be queried using Pa_GetStreamInfo(). If nothing close
  /// to the desired sampleRate is available then the open will fail and return an error.
  ///
  /// @param framesPerBuffer The number of frames passed to the stream callback
  /// function, or the preferred block granularity for a blocking read/write stream.
  /// The special value paFramesPerBufferUnspecified (0) may be used to request that
  /// the stream callback will receive an optimal (and possibly varying) number of
  /// frames based on host requirements and the requested latency settings.
  /// Note: With some host APIs, the use of non-zero framesPerBuffer for a callback
  /// stream may introduce an additional layer of buffering which could introduce
  /// additional latency. PortAudio guarantees that the additional latency
  /// will be kept to the theoretical minimum however, it is strongly recommended
  /// that a non-zero framesPerBuffer value only be used when your algorithm
  /// requires a fixed number of frames per stream callback.
  ///
  /// @param streamFlags Flags which modify the behavior of the streaming process.
  /// This parameter may contain a combination of flags ORed together. Some flags may
  /// only be relevant to certain buffer formats.
  ///
  /// @param streamCallback A pointer to a client supplied function that is responsible
  /// for processing and filling input and output buffers. If this parameter is NULL
  /// the stream will be opened in 'blocking read/write' mode. In blocking mode,
  /// the client can receive sample data using Pa_ReadStream and write sample data
  /// using Pa_WriteStream, the number of samples that may be read or written
  /// without blocking is returned by Pa_GetStreamReadAvailable and
  /// Pa_GetStreamWriteAvailable respectively.
  ///
  /// @param userData A client supplied pointer which is passed to the stream callback
  /// function. It could for example, contain a pointer to instance data necessary
  /// for processing the audio buffers. This parameter is ignored if streamCallback
  /// is NULL.
  ///
  /// @return
  /// Upon success Pa_OpenStream() returns paNoError and places a pointer to a
  /// valid PaStream in the stream argument. The stream is inactive (stopped).
  /// If a call to Pa_OpenStream() fails, a non-zero error code is returned (see
  /// PaError for possible error codes) and the value of stream is invalid.
  ///
  /// @see PaStreamParameters, PaStreamCallback, Pa_ReadStream, Pa_WriteStream,
  /// Pa_GetStreamReadAvailable, Pa_GetStreamWriteAvailable
  int Pa_OpenStream(
    ffi.Pointer<ffi.Pointer<PaStream>> stream,
    ffi.Pointer<PaStreamParameters> inputParameters,
    ffi.Pointer<PaStreamParameters> outputParameters,
    double sampleRate,
    int framesPerBuffer,
    int streamFlags,
    ffi.Pointer<PaStreamCallback> streamCallback,
    ffi.Pointer<ffi.Void> userData,
  ) {
    return _Pa_OpenStream(
      stream,
      inputParameters,
      outputParameters,
      sampleRate,
      framesPerBuffer,
      streamFlags,
      streamCallback,
      userData,
    );
  }

  late final _Pa_OpenStreamPtr = _lookup<
      ffi.NativeFunction<
          PaError Function(
              ffi.Pointer<ffi.Pointer<PaStream>>,
              ffi.Pointer<PaStreamParameters>,
              ffi.Pointer<PaStreamParameters>,
              ffi.Double,
              ffi.Uint64,
              PaStreamFlags,
              ffi.Pointer<PaStreamCallback>,
              ffi.Pointer<ffi.Void>)>>('Pa_OpenStream');
  late final _Pa_OpenStream = _Pa_OpenStreamPtr.asFunction<
      int Function(ffi.Pointer<ffi.Pointer<PaStream>>, ffi.Pointer<PaStreamParameters>, ffi.Pointer<PaStreamParameters>,
          double, int, int, ffi.Pointer<PaStreamCallback>, ffi.Pointer<ffi.Void>)>();

  /// A simplified version of Pa_OpenStream() that opens the default input
  /// and/or output devices.
  ///
  /// @param stream The address of a PaStream pointer which will receive
  /// a pointer to the newly opened stream.
  ///
  /// @param numInputChannels  The number of channels of sound that will be supplied
  /// to the stream callback or returned by Pa_ReadStream. It can range from 1 to
  /// the value of maxInputChannels in the PaDeviceInfo record for the default input
  /// device. If 0 the stream is opened as an output-only stream.
  ///
  /// @param numOutputChannels The number of channels of sound to be delivered to the
  /// stream callback or passed to Pa_WriteStream. It can range from 1 to the value
  /// of maxOutputChannels in the PaDeviceInfo record for the default output device.
  /// If 0 the stream is opened as an output-only stream.
  ///
  /// @param sampleFormat The sample format of both the input and output buffers
  /// provided to the callback or passed to and from Pa_ReadStream and Pa_WriteStream.
  /// sampleFormat may be any of the formats described by the PaSampleFormat
  /// enumeration.
  ///
  /// @param sampleRate Same as Pa_OpenStream parameter of the same name.
  /// @param framesPerBuffer Same as Pa_OpenStream parameter of the same name.
  /// @param streamCallback Same as Pa_OpenStream parameter of the same name.
  /// @param userData Same as Pa_OpenStream parameter of the same name.
  ///
  /// @return As for Pa_OpenStream
  ///
  /// @see Pa_OpenStream, PaStreamCallback
  int Pa_OpenDefaultStream(
    ffi.Pointer<ffi.Pointer<PaStream>> stream,
    int numInputChannels,
    int numOutputChannels,
    int sampleFormat,
    double sampleRate,
    int framesPerBuffer,
    ffi.Pointer<PaStreamCallback> streamCallback,
    ffi.Pointer<ffi.Void> userData,
  ) {
    return _Pa_OpenDefaultStream(
      stream,
      numInputChannels,
      numOutputChannels,
      sampleFormat,
      sampleRate,
      framesPerBuffer,
      streamCallback,
      userData,
    );
  }

  late final _Pa_OpenDefaultStreamPtr = _lookup<
      ffi.NativeFunction<
          PaError Function(ffi.Pointer<ffi.Pointer<PaStream>>, ffi.Int32, ffi.Int32, PaSampleFormat, ffi.Double,
              ffi.Uint64, ffi.Pointer<PaStreamCallback>, ffi.Pointer<ffi.Void>)>>('Pa_OpenDefaultStream');
  late final _Pa_OpenDefaultStream = _Pa_OpenDefaultStreamPtr.asFunction<
      int Function(ffi.Pointer<ffi.Pointer<PaStream>>, int, int, int, double, int, ffi.Pointer<PaStreamCallback>,
          ffi.Pointer<ffi.Void>)>();

  /// Closes an audio stream. If the audio stream is active it
  /// discards any pending buffers as if Pa_AbortStream() had been called.
  int Pa_CloseStream(
    ffi.Pointer<PaStream> stream,
  ) {
    return _Pa_CloseStream(
      stream,
    );
  }

  late final _Pa_CloseStreamPtr =
      _lookup<ffi.NativeFunction<PaError Function(ffi.Pointer<PaStream>)>>('Pa_CloseStream');
  late final _Pa_CloseStream = _Pa_CloseStreamPtr.asFunction<int Function(ffi.Pointer<PaStream>)>();

  /// Register a stream finished callback function which will be called when the
  /// stream becomes inactive. See the description of PaStreamFinishedCallback for
  /// further details about when the callback will be called.
  ///
  /// @param stream a pointer to a PaStream that is in the stopped state - if the
  /// stream is not stopped, the stream's finished callback will remain unchanged
  /// and an error code will be returned.
  ///
  /// @param streamFinishedCallback a pointer to a function with the same signature
  /// as PaStreamFinishedCallback, that will be called when the stream becomes
  /// inactive. Passing NULL for this parameter will un-register a previously
  /// registered stream finished callback function.
  ///
  /// @return on success returns paNoError, otherwise an error code indicating the cause
  /// of the error.
  ///
  /// @see PaStreamFinishedCallback
  int Pa_SetStreamFinishedCallback(
    ffi.Pointer<PaStream> stream,
    ffi.Pointer<PaStreamFinishedCallback> streamFinishedCallback,
  ) {
    return _Pa_SetStreamFinishedCallback(
      stream,
      streamFinishedCallback,
    );
  }

  late final _Pa_SetStreamFinishedCallbackPtr =
      _lookup<ffi.NativeFunction<PaError Function(ffi.Pointer<PaStream>, ffi.Pointer<PaStreamFinishedCallback>)>>(
          'Pa_SetStreamFinishedCallback');
  late final _Pa_SetStreamFinishedCallback = _Pa_SetStreamFinishedCallbackPtr.asFunction<
      int Function(ffi.Pointer<PaStream>, ffi.Pointer<PaStreamFinishedCallback>)>();

  /// Commences audio processing.
  int Pa_StartStream(
    ffi.Pointer<PaStream> stream,
  ) {
    return _Pa_StartStream(
      stream,
    );
  }

  late final _Pa_StartStreamPtr =
      _lookup<ffi.NativeFunction<PaError Function(ffi.Pointer<PaStream>)>>('Pa_StartStream');
  late final _Pa_StartStream = _Pa_StartStreamPtr.asFunction<int Function(ffi.Pointer<PaStream>)>();

  /// Terminates audio processing. It waits until all pending
  /// audio buffers have been played before it returns.
  int Pa_StopStream(
    ffi.Pointer<PaStream> stream,
  ) {
    return _Pa_StopStream(
      stream,
    );
  }

  late final _Pa_StopStreamPtr = _lookup<ffi.NativeFunction<PaError Function(ffi.Pointer<PaStream>)>>('Pa_StopStream');
  late final _Pa_StopStream = _Pa_StopStreamPtr.asFunction<int Function(ffi.Pointer<PaStream>)>();

  /// Terminates audio processing immediately without waiting for pending
  /// buffers to complete.
  int Pa_AbortStream(
    ffi.Pointer<PaStream> stream,
  ) {
    return _Pa_AbortStream(
      stream,
    );
  }

  late final _Pa_AbortStreamPtr =
      _lookup<ffi.NativeFunction<PaError Function(ffi.Pointer<PaStream>)>>('Pa_AbortStream');
  late final _Pa_AbortStream = _Pa_AbortStreamPtr.asFunction<int Function(ffi.Pointer<PaStream>)>();

  /// Determine whether the stream is stopped.
  /// A stream is considered to be stopped prior to a successful call to
  /// Pa_StartStream and after a successful call to Pa_StopStream or Pa_AbortStream.
  /// If a stream callback returns a value other than paContinue the stream is NOT
  /// considered to be stopped.
  ///
  /// @return Returns one (1) when the stream is stopped, zero (0) when
  /// the stream is running or, a PaErrorCode (which are always negative) if
  /// PortAudio is not initialized or an error is encountered.
  ///
  /// @see Pa_StopStream, Pa_AbortStream, Pa_IsStreamActive
  int Pa_IsStreamStopped(
    ffi.Pointer<PaStream> stream,
  ) {
    return _Pa_IsStreamStopped(
      stream,
    );
  }

  late final _Pa_IsStreamStoppedPtr =
      _lookup<ffi.NativeFunction<PaError Function(ffi.Pointer<PaStream>)>>('Pa_IsStreamStopped');
  late final _Pa_IsStreamStopped = _Pa_IsStreamStoppedPtr.asFunction<int Function(ffi.Pointer<PaStream>)>();

  /// Determine whether the stream is active.
  /// A stream is active after a successful call to Pa_StartStream(), until it
  /// becomes inactive either as a result of a call to Pa_StopStream() or
  /// Pa_AbortStream(), or as a result of a return value other than paContinue from
  /// the stream callback. In the latter case, the stream is considered inactive
  /// after the last buffer has finished playing.
  ///
  /// @return Returns one (1) when the stream is active (ie playing or recording
  /// audio), zero (0) when not playing or, a PaErrorCode (which are always negative)
  /// if PortAudio is not initialized or an error is encountered.
  ///
  /// @see Pa_StopStream, Pa_AbortStream, Pa_IsStreamStopped
  int Pa_IsStreamActive(
    ffi.Pointer<PaStream> stream,
  ) {
    return _Pa_IsStreamActive(
      stream,
    );
  }

  late final _Pa_IsStreamActivePtr =
      _lookup<ffi.NativeFunction<PaError Function(ffi.Pointer<PaStream>)>>('Pa_IsStreamActive');
  late final _Pa_IsStreamActive = _Pa_IsStreamActivePtr.asFunction<int Function(ffi.Pointer<PaStream>)>();

  /// Retrieve a pointer to a PaStreamInfo structure containing information
  /// about the specified stream.
  /// @return A pointer to an immutable PaStreamInfo structure. If the stream
  /// parameter is invalid, or an error is encountered, the function returns NULL.
  ///
  /// @param stream A pointer to an open stream previously created with Pa_OpenStream.
  ///
  /// @note PortAudio manages the memory referenced by the returned pointer,
  /// the client must not manipulate or free the memory. The pointer is only
  /// guaranteed to be valid until the specified stream is closed.
  ///
  /// @see PaStreamInfo
  ffi.Pointer<PaStreamInfo> Pa_GetStreamInfo(
    ffi.Pointer<PaStream> stream,
  ) {
    return _Pa_GetStreamInfo(
      stream,
    );
  }

  late final _Pa_GetStreamInfoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<PaStreamInfo> Function(ffi.Pointer<PaStream>)>>('Pa_GetStreamInfo');
  late final _Pa_GetStreamInfo =
      _Pa_GetStreamInfoPtr.asFunction<ffi.Pointer<PaStreamInfo> Function(ffi.Pointer<PaStream>)>();

  /// Returns the current time in seconds for a stream according to the same clock used
  /// to generate callback PaStreamCallbackTimeInfo timestamps. The time values are
  /// monotonically increasing and have unspecified origin.
  ///
  /// Pa_GetStreamTime returns valid time values for the entire life of the stream,
  /// from when the stream is opened until it is closed. Starting and stopping the stream
  /// does not affect the passage of time returned by Pa_GetStreamTime.
  ///
  /// This time may be used for synchronizing other events to the audio stream, for
  /// example synchronizing audio to MIDI.
  ///
  /// @return The stream's current time in seconds, or 0 if an error occurred.
  ///
  /// @see PaTime, PaStreamCallback, PaStreamCallbackTimeInfo
  double Pa_GetStreamTime(
    ffi.Pointer<PaStream> stream,
  ) {
    return _Pa_GetStreamTime(
      stream,
    );
  }

  late final _Pa_GetStreamTimePtr =
      _lookup<ffi.NativeFunction<PaTime Function(ffi.Pointer<PaStream>)>>('Pa_GetStreamTime');
  late final _Pa_GetStreamTime = _Pa_GetStreamTimePtr.asFunction<double Function(ffi.Pointer<PaStream>)>();

  /// Retrieve CPU usage information for the specified stream.
  /// The "CPU Load" is a fraction of total CPU time consumed by a callback stream's
  /// audio processing routines including, but not limited to the client supplied
  /// stream callback. This function does not work with blocking read/write streams.
  ///
  /// This function may be called from the stream callback function or the
  /// application.
  ///
  /// @return
  /// A floating point value, typically between 0.0 and 1.0, where 1.0 indicates
  /// that the stream callback is consuming the maximum number of CPU cycles possible
  /// to maintain real-time operation. A value of 0.5 would imply that PortAudio and
  /// the stream callback was consuming roughly 50% of the available CPU time. The
  /// return value may exceed 1.0. A value of 0.0 will always be returned for a
  /// blocking read/write stream, or if an error occurs.
  double Pa_GetStreamCpuLoad(
    ffi.Pointer<PaStream> stream,
  ) {
    return _Pa_GetStreamCpuLoad(
      stream,
    );
  }

  late final _Pa_GetStreamCpuLoadPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Pointer<PaStream>)>>('Pa_GetStreamCpuLoad');
  late final _Pa_GetStreamCpuLoad = _Pa_GetStreamCpuLoadPtr.asFunction<double Function(ffi.Pointer<PaStream>)>();

  /// Read samples from an input stream. The function doesn't return until
  /// the entire buffer has been filled - this may involve waiting for the operating
  /// system to supply the data.
  ///
  /// @param stream A pointer to an open stream previously created with Pa_OpenStream.
  ///
  /// @param buffer A pointer to a buffer of sample frames. The buffer contains
  /// samples in the format specified by the inputParameters->sampleFormat field
  /// used to open the stream, and the number of channels specified by
  /// inputParameters->numChannels. If non-interleaved samples were requested using
  /// the paNonInterleaved sample format flag, buffer is a pointer to the first element
  /// of an array of buffer pointers, one non-interleaved buffer for each channel.
  ///
  /// @param frames The number of frames to be read into buffer. This parameter
  /// is not constrained to a specific range, however high performance applications
  /// will want to match this parameter to the framesPerBuffer parameter used
  /// when opening the stream.
  ///
  /// @return On success PaNoError will be returned, or PaInputOverflowed if input
  /// data was discarded by PortAudio after the previous call and before this call.
  int Pa_ReadStream(
    ffi.Pointer<PaStream> stream,
    ffi.Pointer<ffi.Void> buffer,
    int frames,
  ) {
    return _Pa_ReadStream(
      stream,
      buffer,
      frames,
    );
  }

  late final _Pa_ReadStreamPtr =
      _lookup<ffi.NativeFunction<PaError Function(ffi.Pointer<PaStream>, ffi.Pointer<ffi.Void>, ffi.Uint64)>>(
          'Pa_ReadStream');
  late final _Pa_ReadStream =
      _Pa_ReadStreamPtr.asFunction<int Function(ffi.Pointer<PaStream>, ffi.Pointer<ffi.Void>, int)>();

  /// Write samples to an output stream. This function doesn't return until the
  /// entire buffer has been written - this may involve waiting for the operating
  /// system to consume the data.
  ///
  /// @param stream A pointer to an open stream previously created with Pa_OpenStream.
  ///
  /// @param buffer A pointer to a buffer of sample frames. The buffer contains
  /// samples in the format specified by the outputParameters->sampleFormat field
  /// used to open the stream, and the number of channels specified by
  /// outputParameters->numChannels. If non-interleaved samples were requested using
  /// the paNonInterleaved sample format flag, buffer is a pointer to the first element
  /// of an array of buffer pointers, one non-interleaved buffer for each channel.
  ///
  /// @param frames The number of frames to be written from buffer. This parameter
  /// is not constrained to a specific range, however high performance applications
  /// will want to match this parameter to the framesPerBuffer parameter used
  /// when opening the stream.
  ///
  /// @return On success PaNoError will be returned, or paOutputUnderflowed if
  /// additional output data was inserted after the previous call and before this
  /// call.
  int Pa_WriteStream(
    ffi.Pointer<PaStream> stream,
    ffi.Pointer<ffi.Void> buffer,
    int frames,
  ) {
    return _Pa_WriteStream(
      stream,
      buffer,
      frames,
    );
  }

  late final _Pa_WriteStreamPtr =
      _lookup<ffi.NativeFunction<PaError Function(ffi.Pointer<PaStream>, ffi.Pointer<ffi.Void>, ffi.Uint64)>>(
          'Pa_WriteStream');
  late final _Pa_WriteStream =
      _Pa_WriteStreamPtr.asFunction<int Function(ffi.Pointer<PaStream>, ffi.Pointer<ffi.Void>, int)>();

  /// Retrieve the number of frames that can be read from the stream without
  /// waiting.
  ///
  /// @return Returns a non-negative value representing the maximum number of frames
  /// that can be read from the stream without blocking or busy waiting or, a
  /// PaErrorCode (which are always negative) if PortAudio is not initialized or an
  /// error is encountered.
  int Pa_GetStreamReadAvailable(
    ffi.Pointer<PaStream> stream,
  ) {
    return _Pa_GetStreamReadAvailable(
      stream,
    );
  }

  late final _Pa_GetStreamReadAvailablePtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<PaStream>)>>('Pa_GetStreamReadAvailable');
  late final _Pa_GetStreamReadAvailable =
      _Pa_GetStreamReadAvailablePtr.asFunction<int Function(ffi.Pointer<PaStream>)>();

  /// Retrieve the number of frames that can be written to the stream without
  /// waiting.
  ///
  /// @return Returns a non-negative value representing the maximum number of frames
  /// that can be written to the stream without blocking or busy waiting or, a
  /// PaErrorCode (which are always negative) if PortAudio is not initialized or an
  /// error is encountered.
  int Pa_GetStreamWriteAvailable(
    ffi.Pointer<PaStream> stream,
  ) {
    return _Pa_GetStreamWriteAvailable(
      stream,
    );
  }

  late final _Pa_GetStreamWriteAvailablePtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<PaStream>)>>('Pa_GetStreamWriteAvailable');
  late final _Pa_GetStreamWriteAvailable =
      _Pa_GetStreamWriteAvailablePtr.asFunction<int Function(ffi.Pointer<PaStream>)>();

  /// Retrieve the size of a given sample format in bytes.
  ///
  /// @return The size in bytes of a single sample in the specified format,
  /// or paSampleFormatNotSupported if the format is not supported.
  int Pa_GetSampleSize(
    int format,
  ) {
    return _Pa_GetSampleSize(
      format,
    );
  }

  late final _Pa_GetSampleSizePtr = _lookup<ffi.NativeFunction<PaError Function(PaSampleFormat)>>('Pa_GetSampleSize');
  late final _Pa_GetSampleSize = _Pa_GetSampleSizePtr.asFunction<int Function(int)>();

  /// Put the caller to sleep for at least 'msec' milliseconds. This function is
  /// provided only as a convenience for authors of portable code (such as the tests
  /// and examples in the PortAudio distribution.)
  ///
  /// The function may sleep longer than requested so don't rely on this for accurate
  /// musical timing.
  void Pa_Sleep(
    int msec,
  ) {
    return _Pa_Sleep(
      msec,
    );
  }

  late final _Pa_SleepPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>('Pa_Sleep');
  late final _Pa_Sleep = _Pa_SleepPtr.asFunction<void Function(int)>();
}

/// A structure containing PortAudio API version information.
/// @see Pa_GetVersionInfo, paMakeVersionNumber
/// @version Available as of 19.5.0.
class PaVersionInfo extends ffi.Struct {
  @ffi.Int32()
  external int versionMajor;

  @ffi.Int32()
  external int versionMinor;

  @ffi.Int32()
  external int versionSubMinor;

  /// This is currently the Git revision hash but may change in the future.
  /// The versionControlRevision is updated by running a script before compiling the library.
  /// If the update does not occur, this value may refer to an earlier revision.
  external ffi.Pointer<ffi.Int8> versionControlRevision;

  /// Version as a string, for example "PortAudio V19.5.0-devel, revision 1952M"
  external ffi.Pointer<ffi.Int8> versionText;
}

abstract class PaErrorCode {
  static const int paNoError = 0;
  static const int paNotInitialized = -10000;
  static const int paUnanticipatedHostError = -9999;
  static const int paInvalidChannelCount = -9998;
  static const int paInvalidSampleRate = -9997;
  static const int paInvalidDevice = -9996;
  static const int paInvalidFlag = -9995;
  static const int paSampleFormatNotSupported = -9994;
  static const int paBadIODeviceCombination = -9993;
  static const int paInsufficientMemory = -9992;
  static const int paBufferTooBig = -9991;
  static const int paBufferTooSmall = -9990;
  static const int paNullCallback = -9989;
  static const int paBadStreamPtr = -9988;
  static const int paTimedOut = -9987;
  static const int paInternalError = -9986;
  static const int paDeviceUnavailable = -9985;
  static const int paIncompatibleHostApiSpecificStreamInfo = -9984;
  static const int paStreamIsStopped = -9983;
  static const int paStreamIsNotStopped = -9982;
  static const int paInputOverflowed = -9981;
  static const int paOutputUnderflowed = -9980;
  static const int paHostApiNotFound = -9979;
  static const int paInvalidHostApi = -9978;
  static const int paCanNotReadFromACallbackStream = -9977;
  static const int paCanNotWriteToACallbackStream = -9976;
  static const int paCanNotReadFromAnOutputOnlyStream = -9975;
  static const int paCanNotWriteToAnInputOnlyStream = -9974;
  static const int paIncompatibleStreamHostApi = -9973;
  static const int paBadBufferPtr = -9972;
}

/// Error codes returned by PortAudio functions.
/// Note that with the exception of paNoError, all PaErrorCodes are negative.
typedef PaError = ffi.Int32;

/// The type used to enumerate to host APIs at runtime. Values of this type
/// range from 0 to (Pa_GetHostApiCount()-1).
///
/// @see Pa_GetHostApiCount
typedef PaHostApiIndex = ffi.Int32;

/// Unchanging unique identifiers for each supported host API. This type
/// is used in the PaHostApiInfo structure. The values are guaranteed to be
/// unique and to never change, thus allowing code to be written that
/// conditionally uses host API specific extensions.
///
/// New type ids will be allocated when support for a host API reaches
/// "public alpha" status, prior to that developers should use the
/// paInDevelopment type id.
///
/// @see PaHostApiInfo
abstract class PaHostApiTypeId {
  static const int paInDevelopment = 0;
  static const int paDirectSound = 1;
  static const int paMME = 2;
  static const int paASIO = 3;
  static const int paSoundManager = 4;
  static const int paCoreAudio = 5;
  static const int paOSS = 7;
  static const int paALSA = 8;
  static const int paAL = 9;
  static const int paBeOS = 10;
  static const int paWDMKS = 11;
  static const int paJACK = 12;
  static const int paWASAPI = 13;
  static const int paAudioScienceHPI = 14;
}

/// A structure containing information about a particular host API.
class PaHostApiInfo extends ffi.Struct {
  /// this is struct version 1
  @ffi.Int32()
  external int structVersion;

  /// The well known unique identifier of this host API @see PaHostApiTypeId
  @ffi.Int32()
  external int type;

  /// A textual description of the host API for display on user interfaces.
  external ffi.Pointer<ffi.Int8> name;

  /// The number of devices belonging to this host API. This field may be
  /// used in conjunction with Pa_HostApiDeviceIndexToDeviceIndex() to enumerate
  /// all devices for this host API.
  /// @see Pa_HostApiDeviceIndexToDeviceIndex
  @ffi.Int32()
  external int deviceCount;

  /// The default input device for this host API. The value will be a
  /// device index ranging from 0 to (Pa_GetDeviceCount()-1), or paNoDevice
  /// if no default input device is available.
  @PaDeviceIndex()
  external int defaultInputDevice;

  /// The default output device for this host API. The value will be a
  /// device index ranging from 0 to (Pa_GetDeviceCount()-1), or paNoDevice
  /// if no default output device is available.
  @PaDeviceIndex()
  external int defaultOutputDevice;
}

/// The type used to refer to audio devices. Values of this type usually
/// range from 0 to (Pa_GetDeviceCount()-1), and may also take on the PaNoDevice
/// and paUseHostApiSpecificDeviceSpecification values.
///
/// @see Pa_GetDeviceCount, paNoDevice, paUseHostApiSpecificDeviceSpecification
typedef PaDeviceIndex = ffi.Int32;

/// Structure used to return information about a host error condition.
class PaHostErrorInfo extends ffi.Struct {
  /// < the host API which returned the error code
  @ffi.Int32()
  external int hostApiType;

  /// < the error code returned
  @ffi.Int64()
  external int errorCode;

  /// < a textual description of the error if available, otherwise a zero-length string
  external ffi.Pointer<ffi.Int8> errorText;
}

/// A structure providing information and capabilities of PortAudio devices.
/// Devices may support input, output or both input and output.
class PaDeviceInfo extends ffi.Struct {
  @ffi.Int32()
  external int structVersion;

  external ffi.Pointer<ffi.Int8> name;

  /// < note this is a host API index, not a type id
  @PaHostApiIndex()
  external int hostApi;

  @ffi.Int32()
  external int maxInputChannels;

  @ffi.Int32()
  external int maxOutputChannels;

  /// Default latency values for interactive performance.
  @PaTime()
  external double defaultLowInputLatency;

  @PaTime()
  external double defaultLowOutputLatency;

  /// Default latency values for robust non-interactive applications (eg. playing sound files).
  @PaTime()
  external double defaultHighInputLatency;

  @PaTime()
  external double defaultHighOutputLatency;

  @ffi.Double()
  external double defaultSampleRate;
}

/// The type used to represent monotonic time in seconds. PaTime is
/// used for the fields of the PaStreamCallbackTimeInfo argument to the
/// PaStreamCallback and as the result of Pa_GetStreamTime().
///
/// PaTime values have unspecified origin.
///
/// @see PaStreamCallback, PaStreamCallbackTimeInfo, Pa_GetStreamTime
typedef PaTime = ffi.Double;

/// Parameters for one direction (input or output) of a stream.
class PaStreamParameters extends ffi.Struct {
  /// A valid device index in the range 0 to (Pa_GetDeviceCount()-1)
  /// specifying the device to be used or the special constant
  /// paUseHostApiSpecificDeviceSpecification which indicates that the actual
  /// device(s) to use are specified in hostApiSpecificStreamInfo.
  /// This field must not be set to paNoDevice.
  @PaDeviceIndex()
  external int device;

  /// The number of channels of sound to be delivered to the
  /// stream callback or accessed by Pa_ReadStream() or Pa_WriteStream().
  /// It can range from 1 to the value of maxInputChannels in the
  /// PaDeviceInfo record for the device specified by the device parameter.
  @ffi.Int32()
  external int channelCount;

  /// The sample format of the buffer provided to the stream callback,
  /// a_ReadStream() or Pa_WriteStream(). It may be any of the formats described
  /// by the PaSampleFormat enumeration.
  @PaSampleFormat()
  external int sampleFormat;

  /// The desired latency in seconds. Where practical, implementations should
  /// configure their latency based on these parameters, otherwise they may
  /// choose the closest viable latency instead. Unless the suggested latency
  /// is greater than the absolute upper limit for the device implementations
  /// should round the suggestedLatency up to the next practical value - ie to
  /// provide an equal or higher latency than suggestedLatency wherever possible.
  /// Actual latency values for an open stream may be retrieved using the
  /// inputLatency and outputLatency fields of the PaStreamInfo structure
  /// returned by Pa_GetStreamInfo().
  /// @see default*Latency in PaDeviceInfo, *Latency in PaStreamInfo
  @PaTime()
  external double suggestedLatency;

  /// An optional pointer to a host api specific data structure
  /// containing additional information for device setup and/or stream processing.
  /// hostApiSpecificStreamInfo is never required for correct operation,
  /// if not used it should be set to NULL.
  external ffi.Pointer<ffi.Void> hostApiSpecificStreamInfo;
}

/// A type used to specify one or more sample formats. Each value indicates
/// a possible format for sound data passed to and from the stream callback,
/// Pa_ReadStream and Pa_WriteStream.
///
/// The standard formats paFloat32, paInt16, paInt32, paInt24, paInt8
/// and aUInt8 are usually implemented by all implementations.
///
/// The floating point representation (paFloat32) uses +1.0 and -1.0 as the
/// maximum and minimum respectively.
///
/// paUInt8 is an unsigned 8 bit format where 128 is considered "ground"
///
/// The paNonInterleaved flag indicates that audio data is passed as an array
/// of pointers to separate buffers, one buffer for each channel. Usually,
/// when this flag is not used, audio data is passed as a single buffer with
/// all channels interleaved.
///
/// @see Pa_OpenStream, Pa_OpenDefaultStream, PaDeviceInfo
/// @see paFloat32, paInt16, paInt32, paInt24, paInt8
/// @see paUInt8, paCustomFormat, paNonInterleaved
typedef PaSampleFormat = ffi.Uint64;

/// Timing information for the buffers passed to the stream callback.
///
/// Time values are expressed in seconds and are synchronised with the time base used by Pa_GetStreamTime() for the associated stream.
///
/// @see PaStreamCallback, Pa_GetStreamTime
class PaStreamCallbackTimeInfo extends ffi.Struct {
  /// < The time when the first sample of the input buffer was captured at the ADC input
  @PaTime()
  external double inputBufferAdcTime;

  /// < The time when the stream callback was invoked
  @PaTime()
  external double currentTime;

  /// < The time when the first sample of the output buffer will output the DAC
  @PaTime()
  external double outputBufferDacTime;
}

/// Allowable return values for the PaStreamCallback.
/// @see PaStreamCallback
abstract class PaStreamCallbackResult {
  /// < Signal that the stream should continue invoking the callback and processing audio.
  static const int paContinue = 0;

  /// < Signal that the stream should stop invoking the callback and finish once all output samples have played.
  static const int paComplete = 1;

  /// < Signal that the stream should stop invoking the callback and finish as soon as possible.
  static const int paAbort = 2;
}

/// A single PaStream can provide multiple channels of real-time
/// streaming audio input and output to a client application. A stream
/// provides access to audio hardware represented by one or more
/// PaDevices. Depending on the underlying Host API, it may be possible
/// to open multiple streams using the same device, however this behavior
/// is implementation defined. Portable applications should assume that
/// a PaDevice may be simultaneously used by at most one PaStream.
///
/// Pointers to PaStream objects are passed between PortAudio functions that
/// operate on streams.
///
/// @see Pa_OpenStream, Pa_OpenDefaultStream, Pa_OpenDefaultStream, Pa_CloseStream,
/// Pa_StartStream, Pa_StopStream, Pa_AbortStream, Pa_IsStreamActive,
/// Pa_GetStreamTime, Pa_GetStreamCpuLoad
typedef PaStream = ffi.Void;

/// Flags used to control the behavior of a stream. They are passed as
/// parameters to Pa_OpenStream or Pa_OpenDefaultStream. Multiple flags may be
/// ORed together.
///
/// @see Pa_OpenStream, Pa_OpenDefaultStream
/// @see paNoFlag, paClipOff, paDitherOff, paNeverDropInput,
/// paPrimeOutputBuffersUsingStreamCallback, paPlatformSpecificFlags
typedef PaStreamFlags = ffi.Uint64;

/// Functions of type PaStreamCallback are implemented by PortAudio clients.
/// They consume, process or generate audio in response to requests from an
/// active PortAudio stream.
///
/// When a stream is running, PortAudio calls the stream callback periodically.
/// The callback function is responsible for processing buffers of audio samples
/// passed via the input and output parameters.
///
/// The PortAudio stream callback runs at very high or real-time priority.
/// It is required to consistently meet its time deadlines. Do not allocate
/// memory, access the file system, call library functions or call other functions
/// from the stream callback that may block or take an unpredictable amount of
/// time to complete.
///
/// In order for a stream to maintain glitch-free operation the callback
/// must consume and return audio data faster than it is recorded and/or
/// played. PortAudio anticipates that each callback invocation may execute for
/// a duration approaching the duration of frameCount audio frames at the stream
/// sample rate. It is reasonable to expect to be able to utilise 70% or more of
/// the available CPU time in the PortAudio callback. However, due to buffer size
/// adaption and other factors, not all host APIs are able to guarantee audio
/// stability under heavy CPU load with arbitrary fixed callback buffer sizes.
/// When high callback CPU utilisation is required the most robust behavior
/// can be achieved by using paFramesPerBufferUnspecified as the
/// Pa_OpenStream() framesPerBuffer parameter.
///
/// @param input and @param output are either arrays of interleaved samples or;
/// if non-interleaved samples were requested using the paNonInterleaved sample
/// format flag, an array of buffer pointers, one non-interleaved buffer for
/// each channel.
///
/// The format, packing and number of channels used by the buffers are
/// determined by parameters to Pa_OpenStream().
///
/// @param frameCount The number of sample frames to be processed by
/// the stream callback.
///
/// @param timeInfo Timestamps indicating the ADC capture time of the first sample
/// in the input buffer, the DAC output time of the first sample in the output buffer
/// and the time the callback was invoked.
/// See PaStreamCallbackTimeInfo and Pa_GetStreamTime()
///
/// @param statusFlags Flags indicating whether input and/or output buffers
/// have been inserted or will be dropped to overcome underflow or overflow
/// conditions.
///
/// @param userData The value of a user supplied pointer passed to
/// Pa_OpenStream() intended for storing synthesis data etc.
///
/// @return
/// The stream callback should return one of the values in the
/// ::PaStreamCallbackResult enumeration. To ensure that the callback continues
/// to be called, it should return paContinue (0). Either paComplete or paAbort
/// can be returned to finish stream processing, after either of these values is
/// returned the callback will not be called again. If paAbort is returned the
/// stream will finish as soon as possible. If paComplete is returned, the stream
/// will continue until all buffers generated by the callback have been played.
/// This may be useful in applications such as soundfile players where a specific
/// duration of output is required. However, it is not necessary to utilize this
/// mechanism as Pa_StopStream(), Pa_AbortStream() or Pa_CloseStream() can also
/// be used to stop the stream. The callback must always fill the entire output
/// buffer irrespective of its return value.
///
/// @see Pa_OpenStream, Pa_OpenDefaultStream
///
/// @note With the exception of Pa_GetStreamCpuLoad() it is not permissible to call
/// PortAudio API functions from within the stream callback.
typedef PaStreamCallback = ffi.NativeFunction<
    ffi.Int32 Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>, ffi.Uint64, ffi.Pointer<PaStreamCallbackTimeInfo>,
        PaStreamCallbackFlags, ffi.Pointer<ffi.Void>)>;

/// Flag bit constants for the statusFlags to PaStreamCallback.
///
/// @see paInputUnderflow, paInputOverflow, paOutputUnderflow, paOutputOverflow,
/// paPrimingOutput
typedef PaStreamCallbackFlags = ffi.Uint64;

/// Functions of type PaStreamFinishedCallback are implemented by PortAudio
/// clients. They can be registered with a stream using the Pa_SetStreamFinishedCallback
/// function. Once registered they are called when the stream becomes inactive
/// (ie once a call to Pa_StopStream() will not block).
/// A stream will become inactive after the stream callback returns non-zero,
/// or when Pa_StopStream or Pa_AbortStream is called. For a stream providing audio
/// output, if the stream callback returns paComplete, or Pa_StopStream() is called,
/// the stream finished callback will not be called until all generated sample data
/// has been played.
///
/// @param userData The userData parameter supplied to Pa_OpenStream()
///
/// @see Pa_SetStreamFinishedCallback
typedef PaStreamFinishedCallback = ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>;

/// A structure containing unchanging information about an open stream.
/// @see Pa_GetStreamInfo
class PaStreamInfo extends ffi.Struct {
  /// this is struct version 1
  @ffi.Int32()
  external int structVersion;

  /// The input latency of the stream in seconds. This value provides the most
  /// accurate estimate of input latency available to the implementation. It may
  /// differ significantly from the suggestedLatency value passed to Pa_OpenStream().
  /// The value of this field will be zero (0.) for output-only streams.
  /// @see PaTime
  @PaTime()
  external double inputLatency;

  /// The output latency of the stream in seconds. This value provides the most
  /// accurate estimate of output latency available to the implementation. It may
  /// differ significantly from the suggestedLatency value passed to Pa_OpenStream().
  /// The value of this field will be zero (0.) for input-only streams.
  /// @see PaTime
  @PaTime()
  external double outputLatency;

  /// The sample rate of the stream in Hertz (samples per second). In cases
  /// where the hardware sample rate is inaccurate and PortAudio is aware of it,
  /// the value of this field may be different from the sampleRate parameter
  /// passed to Pa_OpenStream(). If information about the actual hardware sample
  /// rate is not available, this field will have the same value as the sampleRate
  /// parameter passed to Pa_OpenStream().
  @ffi.Double()
  external double sampleRate;
}

const int paNoDevice = -1;

const int paUseHostApiSpecificDeviceSpecification = -2;

const int paFloat32 = 1;

const int paInt32 = 2;

const int paInt24 = 4;

const int paInt16 = 8;

const int paInt8 = 16;

const int paUInt8 = 32;

const int paCustomFormat = 65536;

const int paNonInterleaved = 2147483648;

const int paFormatIsSupported = 0;

const int paFramesPerBufferUnspecified = 0;

const int paNoFlag = 0;

const int paClipOff = 1;

const int paDitherOff = 2;

const int paNeverDropInput = 4;

const int paPrimeOutputBuffersUsingStreamCallback = 8;

const int paPlatformSpecificFlags = 4294901760;

const int paInputUnderflow = 1;

const int paInputOverflow = 2;

const int paOutputUnderflow = 4;

const int paOutputOverflow = 8;

const int paPrimingOutput = 16;
