import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:ndiscopes/models/colors.dart';
import 'package:ndiscopes/models/textstyles.dart';
import 'package:ndiscopes/providers/frameprovider.dart';
import 'package:ndiscopes/service/ndi/ndi.dart';
import 'package:path/path.dart' as path;
import 'package:path_provider/path_provider.dart';
import 'dart:ui' as ui;
import 'package:provider/provider.dart';

/// The widget displaying only the rgba frame downscaled to 160x90 using a custom paint
class NDIFrameThumbnail extends StatefulWidget {
  final File file;
  const NDIFrameThumbnail({
    Key? key,
    required this.file,
  }) : super(key: key);

  @override
  State<NDIFrameThumbnail> createState() => _NDIFrameThumbnailState();
}

class _NDIFrameThumbnailState extends State<NDIFrameThumbnail> {
  late SavedInputFrame frame;
  ui.Image? img;

  @override
  void initState() {
    super.initState();
    // read the file and convert
    init();
  }

  init() async {
    frame = SavedInputFrame.fromJSON(jsonDecode(await widget.file.readAsString()));
    if (img == null) {
      frame.thumbnailImage().then(
        (i) {
          // only setState if the frame Browser is still open/"mounted"
          // otherwise it would call setState after dispose
          // causes unhandled Exception
          if (mounted) {
            setState(() {
              img = i;
            });
          }
        },
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    if (img != null) {
      return SizedBox(
        child: FittedBox(
          fit: BoxFit.contain,
          child: CustomPaint(
            size: const Size(160, 90),
            painter: ThumbnailPainter(img: img!),
          ),
        ),
      );
    } else {
      return const Icon(
        Icons.image_sharp,
        color: Colors.white,
        size: 35,
      );
    }
  }
}

class ThumbnailPainter extends CustomPainter {
  final ui.Image img;
  ThumbnailPainter({required this.img});
  @override
  void paint(Canvas canvas, Size size) {
    //canvas.drawPaint(Paint()..color = Colors.black);
    canvas.drawImage(
      img,
      Offset.zero,
      Paint()
        ..colorFilter = const ColorFilter.matrix(
          <double>[
            1, 0, 0, 0, 0, //
            0, 1, 0, 0, 0, //
            0, 0, 1, 0, 0, //
            0, 0, 0, 1, 0, //
          ],
        ),
    );
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return false;
  }
}

class FrameBrowserV2 extends StatefulWidget {
  const FrameBrowserV2({Key? key}) : super(key: key);

  @override
  State<FrameBrowserV2> createState() => _FrameBrowserV2State();
}

class _FrameBrowserV2State extends State<FrameBrowserV2> {
  Directory? currentDir;
  late Directory appDir;
  late FocusNode fn;
  bool _hasFocus = false;

  @override
  void initState() {
    super.initState();
    fn = FocusNode();
    fn.addListener(focusListener);
    //initiate application directory and listener
    init();
  }

  @override
  void dispose() {
    fn.removeListener(focusListener);
    fn.dispose();

    super.dispose();
  }

  void focusListener() {
    setState(() {
      _hasFocus = fn.hasFocus;
    });
  }

  //all contents of the application directory
  List<FileSystemEntity> appDirContents = [];
  //sorted directories of application directory
  List<Directory> appDirDirectorys = [];
  //all contents of the selected subdirectory
  List<FileSystemEntity> currentDirContents = [];

  Future<void> init() async {
    // find the aopplication directory in documents
    final docDir = await getApplicationDocumentsDirectory();
    appDir = Directory(docDir.path + "/NDIScopes");

    // create if it doesn't exist and list all subderictories
    await updateAppDir();

    // initiate listener to check for changes in the application directory
    appDir.watch(recursive: true).listen((event) async {
      // fetch new subdirectories
      await updateAppDir();
      // fetch frames in current subdirectory
      await updateCurrentDir();
      setState(() {});
    });
    // if there are no subdirectories stop
    if (appDirDirectorys.isEmpty) return;
    // set the latest directory as the initial
    currentDir = appDirDirectorys.last;
    // fetch frames of initial subdirectory
    await updateCurrentDir();
    setState(() {});
  }

  Future<void> updateAppDir() async {
    if (!await appDir.exists()) await appDir.create();
    // get all entities in application directory
    appDirContents = [];
    final fseStream = appDir.list(followLinks: false, recursive: false);

    await for (FileSystemEntity fse in fseStream) {
      appDirContents.add(fse);
    }

    // only consider subdirectories and ignore files
    appDirDirectorys = appDirContents.whereType<Directory>().toList();
    // sort all subdirectories by name (as int because the names are autogenerated to be the date of creation)
    appDirDirectorys.sort(
      (a, b) => int.parse(path.basename(a.path)).compareTo(
        int.parse(path.basename(b.path)),
      ),
    );
    // if we not jet have a directory selected and there are directories to select from set the latest directory as initial
    //if (currentDir == null && appDirDirectorys.isNotEmpty)
    currentDir = appDirDirectorys.isNotEmpty ? appDirDirectorys.last : null;
  }

  Future<void> updateCurrentDir() async {
    // dont update if no dir selected
    if (currentDir == null) return;
    // fetch all entities, might cause exception if current dir now longer exists
    try {
      currentDirContents = currentDir!.listSync(recursive: false, followLinks: false);
    } catch (e) {
      currentDir = null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      color: cPrimary,
      child: Column(
        mainAxisSize: MainAxisSize.max,
        children: [
          if (appDirDirectorys.isNotEmpty && currentDir != null && appDirDirectorys.contains(currentDir))
            DropdownButton<Directory>(
              focusNode: fn,
              value: currentDir,
              underline: _hasFocus
                  ? Container(
                      height: 2,
                      color: cFocused,
                    )
                  : Container(),
              style: tThin,
              items: List<DropdownMenuItem<Directory>>.generate(
                appDirDirectorys.length,
                (index) => DropdownMenuItem<Directory>(
                  child: Center(
                    child: Text(
                      path.basename(appDirDirectorys[index].path),
                      style: tSmall,
                      textAlign: TextAlign.center,
                    ),
                  ),
                  value: appDirDirectorys[index],
                  key: ValueKey(appDirDirectorys[index]),
                ),
              ),
              onChanged: (d) {
                if (d != null) currentDir = d;
                updateCurrentDir();
                setState(() {});
              },
              dropdownColor: cDialogBackground,
            ),
          if (appDirDirectorys.isEmpty)
            Padding(
              padding: const EdgeInsets.all(8),
              child: Text(
                "No Frames",
                style: tSmall,
              ),
            ),
          Expanded(
            child: ListView.builder(
              itemCount: currentDirContents.length,
              // for every file system entry in the current dir
              itemBuilder: (context, index) {
                final fse = currentDirContents[index];
                // ignore files that don't end with ".ndis" and directories
                if (fse is File && path.extension(fse.path) == ".ndis") {
                  return Padding(
                    padding: const EdgeInsets.all(8),
                    child: Material(
                      color: Colors.transparent,
                      child: InkWell(
                        onTap: () {
                          // read data from file and create frame and scopes
                          SavedInputFrame.fromJSON(
                            jsonDecode(
                              fse.readAsStringSync(),
                            ),
                          ).convertToScopesPointer().then(
                                (value) => context.read<Frame>().toggleOverlay(enabled: true),
                              );
                        },
                        overlayColor: MaterialStateProperty.resolveWith((states) {
                          if (states.contains(MaterialState.hovered)) return cHighlight;
                          if (states.contains(MaterialState.focused)) return cFocused;
                          return Colors.transparent;
                        }),
                        child: Padding(
                          padding: const EdgeInsets.all(2.0),
                          child: NDIFrameThumbnail(
                            file: fse,
                            key: ValueKey(fse),
                          ),
                        ),
                      ),
                    ),
                  );
                } else {
                  return Container();
                }
              },
            ),
          ),
        ],
      ),
    );
  }
}
